export default {
	// Common
	LOADING: 'LOADING',
	SHOWINTRO: 'SHOWINTRO',
	LANGUAGECODE: 'LANGUAGECODE',
	SETCURRENCY: 'SETCURRENCY',
	SHOWMODAL: 'SHOWMODAL',
	RESETSTATE: 'RESETSTATE',

	SETBUDGET: 'SETBUDGET',
	BACKUPTRANSACTION: 'BACKUPTRANSACTION',
	RESTORETRANSACTION: 'RESTORETRANSACTION',
	BACKUPACCOUNT: 'BACKUPACCOUNT',
	RESTOREACCOUNT: 'RESTOREACCOUNT',
	RESTOREBILLS: 'RESTOREBILLS',
	RESETTRANSACTIONS: 'RESETTRANSACTIONS',
	RESETACCOUNTS: 'RESETACCOUNTS',
	RESETSETTINGS: 'RESETSETTINGS',
	RESETBILLS: 'RESETBILLS',

	// Auth
	SIGNUP : 'SIGNUP',
	SIGNIN : 'SIGNIN',
	LOGOUT : 'LOGOUT',
	FORGOTPASSWORD : 'FORGOTPASSWORD',

	// Accounts
	ADDACC : 'ADDACC',
	REMOVEACC : 'REMOVEACC',
	ADDBANKACC : 'ADDBANKACC',
	REMOVEBANKACC : 'REMOVEBANKACC',
	ADDWALLETACC : 'ADDWALLETACC',
	REMOVEWALLETACC : 'REMOVEWALLETACC',
	UPDATEACCOUNTTOTAL : 'UPDATEACCOUNTTOTAL',
	UPDATEACCOUNTTOTAL : 'UPDATEACCOUNTTOTAL',
	UPDATEACCOUNTTRANSFERTOTAL : 'UPDATEACCOUNTTRANSFERTOTAL',

	// Transactions
	ADDTRANSACTION : 'ADDTRANSACTION',
	REMOVETRANSACTION : 'REMOVETRANSACTION',
	
	// Biller
	ADDBILLER : 'ADDBILLER',
	REMOVEBILLER : 'REMOVEBILLER',
	GENERATEBILLS : 'GENERATEBILLS',
	PAIDWITHBILLER : 'PAIDWITHBILLER',

};