export default {
	// Common
	LOADING: 'LOADING',
	SHOWINTRO: 'SHOWINTRO',
	LANGUAGECODE: 'LANGUAGECODE',
	SETCURRENCY: 'SETCURRENCY',
	SHOWMODAL: 'SHOWMODAL',
	RESETSTATE: 'RESETSTATE',

	// Auth
	SIGNUP : 'SIGNUP',
	SIGNIN : 'SIGNIN',
	LOGOUT : 'LOGOUT',
	FORGOTPASSWORD : 'FORGOTPASSWORD',

	// Accounts
	ADDBANKACC : 'ADDBANKACC',
	REMOVEBANKACC : 'REMOVEBANKACC',
	ADDWALLETACC : 'ADDWALLETACC',
	REMOVEWALLETACC : 'REMOVEWALLETACC',

	// Transactions
	ADDTRANSACTION : 'ADDTRANSACTION',
	REMOVETRANSACTION : 'REMOVETRANSACTION',
	

};