export default[
	{
		id: 0,
		lang: 'English',
		langCode: 'en',
		appName: 'MyPerFi',
		signinTitle: 'Signin to Get Started!',
		email: 'Email',
		name: 'Name',
		password: 'Password',
		confirmPassword: 'Confirm Password',
		createAcc: 'Create Account',
		forgot: 'Forgot Password',
		signin: 'Sign In',
		signup: 'Sign Up',
		reset: 'Reset',
		logout: 'Logout',

		home: 'Home',
		categories: 'Categories',
		accounts: 'Accounts',
		accountsSub: 'Manage your accounts',
		settings: 'Settings',
		bankacc: 'Bank Accounts',
		wallets: 'Wallets',

		// App intro sliders
		slide1Title: 'TRACK YOUR MONEY',
		slide1Text: 'It helps you to track your\nexpenses quickly and easily.',
		slide2Title: 'UNDERSTAND YOUR FINANCES',
		slide2Text: 'Overview your past and current\nspending progress by category.',
		slide3Title: 'ORGANIZE YOUR FINANCES',
		slide3Text: 'Easy and user friendly Personal\nFinance App to take control of\nyour money.',

		//Validation messages
		required: 'is required',
		notValid: 'is not valid',
		tooShort: 'Minimum {count, number} chars required',
		doesntMatch: 'doesn\'t match',
	},
	{
		id: 1,
		lang: 'தமிழ்',
		langCode: 'ta',
		appName: 'புஷ்பேஸ்',
		signinTitle: 'தொடங்க உள்நுழைக!',
		email: 'மின்னஞ்சல்',
		name: 'பெயர்',
		password: 'கடவுச்சொல்',
		confirmPassword: 'கடவுச்சொல்லை உறுதிப்படுத்தவும்',
		createAcc: 'கணக்கை துவங்குங்கள்',
		forgot: 'கடவுச்சொல்லை மறந்துவிட்டீர்களா',
		signin: 'உள்நுழை',
		signup: 'பதிவு செய்',
		reset: 'மீட்டமை',
		logout: 'வெளியேறு',

		home: 'முகப்பு',
		categories: 'வகைகள்',
		accounts: 'கணக்குகள்',
		accountsSub: 'உங்கள் கணக்குகளை நிர்வகிக்கவும்',
		settings: 'அமைப்புகள்',
		bankacc: 'வங்கி கணக்குகள்',
		wallets: 'பணப்பைகள்',

		// App intro sliders
		slide1Title: 'உங்கள் பணத்தை கண்காணிக்கவும்',
		slide1Text: 'உங்கள் செலவுகளை விரைவாகவும்\nஎளிதாகவும் கண்காணிக்க இது உதவுகிறது.',
		slide2Title: 'உங்கள் நிதிகளைப் புரிந்து கொள்ளுங்கள்',
		slide2Text: 'உங்கள் கடந்த கால மற்றும் தற்போதைய\nசெலவு முன்னேற்றத்தை வகைப்படுத்த உதவுகிறது.',
		slide3Title: 'உங்கள் நிதிகளை ஒழுங்கமைக்கவும்',
		slide3Text: 'உங்கள் பணத்தை கட்டுப்படுத்த எளிதான\nமற்றும் பயனர் நட்பு தனிப்பட்ட நிதி பயன்பாடு.',

		//Validation messages
		required: 'தேவை',
		notValid: 'சரியானது அல்ல',
		tooShort: 'குறைந்தபட்சம் {count, number} எழுத்துகள் தேவை',
		doesntMatch: 'பொருந்தவில்லை',
	}
];