export default[
	{
		id: 0,
		lang: 'English',
		langCode: 'en',
		appName: 'MyPerFi',
		signinTitle: 'Signin to Get Started!',
		email: 'Email',
		name: 'Name',
		password: 'Password',
		confirmPassword: 'Confirm Password',
		createAcc: 'Create Account',
		forgot: 'Forgot Password',
		signin: 'Sign In',
		signup: 'Sign Up',
		reset: 'Reset',
		logout: 'Logout',
		current: 'Current',
		income: 'Income',
		expense: 'Expense',
		delete: 'Delete',
		confirm: 'Confirm',
		okay: 'Okay',
		cancel: 'Cancel',

		latestTrans: 'Latest Transactions',
		topSpend: 'Top Spend Areas',
		bills: 'Bills',

		home: 'Home',
		bankacc: 'Bank Accounts',
		wallets: 'Wallets',

		// Settings page
		settings: 'Settings',
		chooseLang: 'Choose Language',
		chooseCurr: 'Choose Currency',

		// Accounts page
		accounts: 'Accounts',
		manageAcc: 'Manage your accounts',
		totalBalance: 'Total Balance',
		addBankacc: 'Add Bank Account',
		editBankacc: 'Update Bank Account',
		addWallet: 'Add Wallet Account',
		editWallet: 'Update Wallet Account',
		accName: 'Account Name',
		accNo: 'Account No',
		last4: 'Last 4 digits',
		accNoEx: 'Ex - x0000',
		accBal: 'Account Balance',
		accAct: 'Account is active',
		walName: 'Wallet Name',
		walBal: 'Wallet Balance',
		walAct: 'Wallet is active',
		delAccConfirm: 'All the transaction associated with this account will be deleted. Do you want to continue?',


		added: 'Added successfully',
		deleted: 'Deleted successfully',
		updated: 'Updated successfully',

		// Categories page
		categories: 'Categories',
		manageCat: 'Manage your categories',

		// App intro sliders
		slide1Title: 'TRACK YOUR MONEY',
		slide1Text: 'It helps you to track your\nexpenses quickly and easily.',
		slide2Title: 'UNDERSTAND YOUR FINANCES',
		slide2Text: 'Overview your past and current\nspending progress by category.',
		slide3Title: 'ORGANIZE YOUR FINANCES',
		slide3Text: 'Easy and user friendly Personal\nFinance App to take control of\nyour money.',

		//Validation messages
		required: 'is required',
		notValid: 'is not valid',
		tooShort: 'Minimum {count, number} chars required',
		doesntMatch: 'doesn\'t match',

		// Currency
		inr: 'Rupees',
		usd: 'Dollar',
		euro: 'Euro',

		// Categories
		transfer: 'Transfer',
		moneytransfer: 'Account Transfer',
		salary: 'Salary',
		savings: 'Savings',
		gift: 'Gifts',
		interest: 'Interest',
		investmentincome: 'Investment Income',
		loan: 'Loan',
		mutualfund: 'Mutual Funds',
		others: 'Others',
		work: 'Work',
		refund: 'Refund',

		airticket: 'Air Ticket',
		beauty: 'Beauty',
		bike: 'Bike',
		bill: 'Bills/Utilities',
		book: 'Books',
		breakfast: 'Breakfast',
		business: 'Business',
		car: 'Car',
		chicken: 'Chicken',
		child: 'Child',
		clothes: 'Clothes',
		coffee: 'Coffee',
		cookies: 'Cookies',
		courier: 'Courier',
		cycle: 'Cycle',
		dining: 'Dining',
		dinner: 'Dinner',
		donation: 'Donation',
		drinks: 'Drinks',
		education: 'Education',
		electricity: 'Electricity',
		electronics: 'Electronics',
		emi:'EMI',
		entertainment:'Entertainment',
		fastfood:'Fast Food',
		finance:'Finance',
		flowers:'Flowers',
		fooddrinks:'Food & Drinks',
		fruits:'Fruits',
		games:'Games',
		gas:'Gas',
		grocery:'Grocery',
		gymfitness:'Gym',
		health:'Health',
		heart: 'Heart',
		hotel: 'Hotel',
		house: 'House',
		icecream: 'Ice Cream',
		imps: 'IMPS',
		insurance: 'Insurance',
		investment: 'Investment',
		jewellery: 'Jewellery',
		job: 'Job',
		loan: 'Loan',
		lunch: 'Lunch',
		maid: 'Maid',
		maintenance: 'Maintenance',
		medical: 'Medical',
		milk: 'Milk',
		misc: 'Miscellaneous',
		mobile: 'Mobile',
		month: 'Monthly',
		music: 'Music',
		pay: 'Pay',
		pet: 'Pets',
		rent: 'Rent',
		saloon: 'Saloon',
		shoes: 'Shoes',
		shopping: 'Shopping',
		spa: 'Spa',
		stationery: 'Stationery',
		tax: 'Tax',
		taxi: 'Taxi',
		ticket: 'Ticket',
		toy: 'Toys',
		train: 'Train',
		travel: 'Travel',
		tv: 'TV',
		vacation: 'Vacation',
		vegtables: 'Vegtables',
		wallet: 'Wallet',
		water: 'Water',

	},
	{
		id: 1,
		lang: 'தமிழ்',
		langCode: 'ta',
		appName: 'புஷ்பேஸ்',
		signinTitle: 'தொடங்க உள்நுழைக!',
		email: 'மின்னஞ்சல்',
		name: 'பெயர்',
		password: 'கடவுச்சொல்',
		confirmPassword: 'கடவுச்சொல்லை உறுதிப்படுத்தவும்',
		createAcc: 'கணக்கை துவங்குங்கள்',
		forgot: 'கடவுச்சொல்லை மறந்துவிட்டீர்களா',
		signin: 'உள்நுழை',
		signup: 'பதிவு செய்',
		reset: 'மீட்டமை',
		logout: 'வெளியேறு',
		current: 'தற்போதைய',
		income: 'வருவாய்',
		expense: 'செலவு',
		delete: 'நீக்கு',
		confirm: 'உறுதிப்படுத்தவும்',
		okay: 'சரி',
		cancel: 'ரத்துசெய்',

		latestTrans: 'சமீபத்திய பரிவர்த்தனைகள்',
		topSpend: 'அதிக செலவு பகுதிகள்',
		bills: 'ரசிதுகள்',

		home: 'முகப்பு',
		bankacc: 'வங்கி கணக்குகள்',
		wallets: 'பணப்பைகள்',

		// Settings page
		settings: 'அமைப்புகள்',
		chooseLang: 'மொழியைத் தேர்வுசெய்க',
		chooseCurr: 'நாணயத்தைத் தேர்வுசெய்க',

		// Accounts page
		accounts: 'கணக்குகள்',
		manageAcc: 'உங்கள் கணக்குகளை நிர்வகிக்கவும்',
		totalBalance: 'மொத்த இருப்பு',
		addBankacc: 'வங்கி கணக்கைச் சேர்க்கவும்',
		editBankacc: 'வங்கி கணக்கைப் புதுப்பிக்கவும்',
		addWallet: 'பணப்பை கணக்கைச் சேர்க்கவும்',
		editWallet: 'பணப்பை கணக்கைப் புதுப்பிக்கவும்',
		accName: 'கணக்கின் பெயர்',
		accNo: 'கணக்கு எண்',
		last4: 'கடைசி 4 இலக்கங்கள்',
		accNoEx: 'உதாரணம் - x0000',
		accBal: 'கணக்கு இருப்பு',
		accAct: 'கணக்கு செயலில் உள்ளது',
		walName: 'பணப்பை பெயர்',
		walBal: 'பணப்பை இருப்பு',
		walAct: 'பணப்பை செயலில் உள்ளது',
		delAccConfirm: 'இந்த கணக்குடன் தொடர்புடைய அனைத்து பரிவர்த்தனைகளும் நீக்கப்படும். நீங்கள் தொடர விரும்புகிறீர்களா?',


		added: 'வெற்றிகரமாக சேர்க்கப்பட்டது',
		deleted: 'வெற்றிகரமாக நீக்கப்பட்டது',
		updated: 'வெற்றிகரமாக புதுப்பிக்கப்பட்டது',

		// Categories page
		categories: 'வகைகள்',
		manageCat: 'உங்கள் வகைகளை நிர்வகிக்கவும்',

		// App intro sliders
		slide1Title: 'உங்கள் பணத்தை கண்காணிக்கவும்',
		slide1Text: 'உங்கள் செலவுகளை விரைவாகவும்\nஎளிதாகவும் கண்காணிக்க இது உதவுகிறது.',
		slide2Title: 'உங்கள் நிதிகளைப் புரிந்து கொள்ளுங்கள்',
		slide2Text: 'உங்கள் கடந்த கால மற்றும் தற்போதைய\nசெலவு முன்னேற்றத்தை வகைப்படுத்த உதவுகிறது.',
		slide3Title: 'உங்கள் நிதிகளை ஒழுங்கமைக்கவும்',
		slide3Text: 'உங்கள் பணத்தை கட்டுப்படுத்த எளிதான\nமற்றும் பயனர் நட்பு தனிப்பட்ட நிதி பயன்பாடு.',

		//Validation messages
		required: 'தேவை',
		notValid: 'சரியானது அல்ல',
		tooShort: 'குறைந்தபட்சம் {count, number} எழுத்துகள் தேவை',
		doesntMatch: 'பொருந்தவில்லை',

		// Currency
		inr: 'ரூபாய்',
		usd: 'டாலர்',
		euro: 'யூரோ',

		// Categories
		transfer: 'பரிமாற்றம்',
		moneytransfer: 'கணக்கு பரிமாற்றம்',
		salary: 'ஊதியம்',
		savings: 'சேமிப்பு',
		gift: 'பரிசுகள்',
		interest: 'வட்டி',
		investmentincome: 'முதலீட்டு வருமானம்',
		loan: 'கடன்',
		mutualfund: 'பரஸ்பர நிதி',
		others: 'மற்றவைகள்',
		work: 'வேலை',
		refund: 'திருப்பிக்கொடுத்தல்',

		airticket: 'விமான பயணசீட்டு',
		beauty: 'அழகு',
		bike: 'வண்டி',
		bill: 'ரசிது/பயன்பாடுகள்',
		book: 'புத்தகங்கள்',
		breakfast: 'காலை உணவு',
		business: 'வணிகம்',
		car: 'ஊர்தி',
		chicken: 'கோழி',
		child: 'குழந்தை',
		clothes: 'ஆடைகள்',
		coffee: 'காப்பி',
		cookies: 'தின்பண்டங்கள்',
		courier: 'கூரியர்',
		cycle: 'மிதிவண்டி',
		dining: 'சாப்பாட்டு',
		dinner: 'இரவு சாப்பாடு',
		donation: 'நன்கொடை',
		drinks: 'பானங்கள்',
		education: 'கல்வி',
		electricity: 'மின்சாரம்',
		electronics: 'மின்னணு',
		emi:'மாதாந்திர தவணை',
		entertainment:'பொழுதுபோக்கு',
		fastfood:'துரித உணவு',
		finance:'நிதி',
		flowers:'மலர்கள்',
		fooddrinks:'உணவு & பானங்கள்',
		fruits:'பழங்கள்',
		games:'விளையாட்டுகள்',
		gas:'எரிவாயு',
		grocery:'மளிகை',
		gymfitness:'கூடம்',
		health:'சுகாதாரம்',
		heart: 'இதயம்',
		hotel: 'தங்கும் விடுதி',
		house: 'வீடு',
		icecream: 'பனி கூழ்',
		imps: 'ஐஎம்பிஎஸ்',
		insurance: 'காப்பீடு',
		investment: 'முதலீடு',
		jewellery: 'அணிகலன்கள்',
		job: 'வேலை',
		loan: 'கடன்',
		lunch: 'மதிய உணவு',
		maid: 'பணிப்பெண்',
		maintenance: 'பராமரிப்பு',
		medical: 'மருத்துவம்',
		milk: 'பால்',
		misc: 'இதரம்',
		mobile: 'கைப்பேசி',
		month: 'மாதாந்திரம்',
		music: 'இசை',
		pay: 'செலுத்து',
		pet: 'செல்லப்பிராணிகள்',
		rent: 'வாடகை',
		saloon: 'சலூன்',
		shoes: 'காலணிகள்',
		shopping: 'பொருட்கள் வாங்குதல்',
		spa: 'ஸ்பா',
		stationery: 'எழுது பொருள்கள்',
		tax: 'வரி',
		taxi: 'வாடகை ஊர்தி',
		ticket: 'பயணச்சீட்டு',
		toy: 'பொம்மைகள்',
		train: 'ரயில்',
		travel: 'சுற்றுலா',
		tv: 'தொலைக்காட்சி',
		vacation: 'விடுமுறை',
		vegtables: 'காய்கறிகள்',
		wallet: 'கைப்பை',
		water: 'தண்ணீர்',
	}
];